Repository uber-workflow/probot-app-pr-title, pull requests merged in 2019-05, with the labels that each got.

#74 Add 'instrument' to imperative verb whitelist
  validate-title.js
Labels: bugfix

#75 Upgrade probot
  package.json
  yarn.lock
Labels: greenkeeping

#76 Release v1.1.8-0
  package.json
Labels: release

#77 Add `sync` to valid verbs
  __tests__/validate-title.js
  validate-title.js
Labels: bugfix

#78 Release v1.1.8-1
  package.json
Labels: release

#79 Add throw to list of imperative verbs
  validate-title.js
Labels: bugfix
